---
- hosts: localhost
  connection: local
  tasks:
    - tower_credential:
        name: open1
        organization: Default
        kind: openstack
        state: present
        username: admin
        password: c0ntrail123
        host: http://172.31.190.16:5000/v3
        project: SE-Apple
        domain: admin_domain
        user: admin_awx
        tower_verify_ssl: yes
        tower_config_file: "~/.tower_cli.cfg"
