---
- hosts: all
  tasks:
    - name: creating credentials
      tower_credential:
        name: open1
        organization: Default
        kind: openstack
        state: present
        username: admin
        password: c0ntrail123
        host: https://172.31.248.11:5000/v3
        project: Prepod-App
        domain: admin_domain
        verify_ssl: false
        user: admin_awx
        tower_verify_ssl: no
        tower_config_file: "~/.tower_cli.cfg"
